ARG IMAGE v0.2.41-gpu

FROM ghcr.io/open-flux-ai/serve/llama-cpp-python:${IMAGE}

COPY model.gguf /models/

ENTRYPOINT ["python3", "-m", "llama_cpp.server", "--model", "/models/model.gguf", "--n_gpu_layers", "-1", "--n_threads", "16"]
